# Generated by Django 3.2.3 on 2021-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skintoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimagedb',
            name='user_image',
            field=models.ImageField(upload_to='user_image'),
        ),
    ]
